import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Booking from "./components/Booking/Booking";
import SideButton from "./components/SideButton/SideButton";
import Banner from "./components/Banner/Banner";
import Subscribe from "./components/Subscribe/Subscribe";
import Steps from "./components/Steps/Steps";
import Location from "./components/Location/Location";
import Faq from "./components/Faq/Faq";
import Footer from "./components/Footer/Footer";
import PopularCarsSection from "./components/PopularCarsSection/PopularCarsSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DiamontLease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
